# config/sidekiq.yml
:concurrency: 3 #how many workers you want to run by sidekiq
:timeout: 60 #
:verbose: true
:queues:  # Queue priority: https://github.com/mperham/sidekiq/wiki/Advanced-Options
  - default
  - mailers
